# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "Bitbucket CLI - a command-line tool for Bitbucket"
  homepage "https://bitbucket.org/git-m4u/bitbucket-cli"
  version "0.1.2"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Bemobi-Org/homebrew-bitbucket-cli/releases/download/v0.1.2/homebrew-bitbucket-cli_0.1.2_darwin_amd64.tar.gz"
    sha256 "554ec2ed08b64d56570a2030f04dce86c3cffd0700808f47f3270d75fe2b7766"

    define_method(:install) do
      bin.install "bb"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Bemobi-Org/homebrew-bitbucket-cli/releases/download/v0.1.2/homebrew-bitbucket-cli_0.1.2_darwin_arm64.tar.gz"
    sha256 "383da571159ea842d0973249b6726f4cee9f43b2487376b0476529949b4227ab"

    define_method(:install) do
      bin.install "bb"
    end
  end
end
