# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewBitbucketCli < Formula
  desc "Bitbucket CLI - a command-line tool for Bitbucket"
  homepage "https://bitbucket.org/git-m4u/bitbucket-cli"
  version "0.1.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Bemobi-Org/homebrew-bitbucket-cli/releases/download/v0.1.1/homebrew-bitbucket-cli_0.1.1_darwin_amd64.tar.gz"
    sha256 "fd3267147b7bef26f08ce5a9db54a0dabda929c0bf69b00dded3d4cbf14c3e3b"

    define_method(:install) do
      bin.install "bb"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Bemobi-Org/homebrew-bitbucket-cli/releases/download/v0.1.1/homebrew-bitbucket-cli_0.1.1_darwin_arm64.tar.gz"
    sha256 "c50f59e87e3e3d99ec28486643edd74ea28f1e0a54529e1521c90387eb5b7ff0"

    define_method(:install) do
      bin.install "bb"
    end
  end
end
